### ISSUE TITLE
wake sleep duration can't be set to 0

### ISSUE THREAD

**Issue by Hascki** [qtoggle/espqtoggle#84]
**Describe the bug:**
wake sleep duration can't be set to 0

**Steps to reproduce:**
get a device
set wake sleep duration to 20 s and sleep wake interval to 3 minutes
apply
set sleep wake interval to 0 (to disable sleep)
set sleep wake duration to 0 (just to be sure)
apply
get an error (invalid value)

**Expected behavior:**
Should allow for 0 if wake duration is also 0

**Comment by ccrisan** [comment]
Fixed via e8748ebba2302a87035c0e96dd72aa1280b8aa7e.
