### ISSUE TITLE
PWM is wrong

### ISSUE THREAD

**Issue by Hascki** [qtoggle/espqtoggle#88]
**Describe the bug:**
The lights go to full(or 0) then back to expected value

**Steps to reproduce:**
set new value, wait 1 sec

**Comment by ccrisan** [comment]
Fixed via 073733117273ed28defd4d36b815ace64a1ae3d2.

**Comment by ccrisan** [comment]
For the record, disabling interrupts while reading/writing from/to SPI flash seemed like a good idea at first, but it messes up timers and other time-constrained operations.
